import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Autorization } from "@/components/autorization/Autorization";
import { Bounce, ToastContainer } from "react-toastify";
import { Montserrat } from 'next/font/google';
import { Loading } from "@/components/loading/Loading";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-montserrat', // Variável CSS personalizada
})

export const metadata: Metadata = {
  title: "App PasBem",
  description: "Generated by create next app",
  manifest: '/aplicativo/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="manifest" href="/aplicativo/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`${montserrat.variable} antialiased`}>
        <Loading />
        <Autorization />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
        />
        {children}
      </body>
    </html>
  );
}
